### PR TITLE
Redo potgrator

### PR DESCRIPTION
**Pull request by Pprime1**
Rebaselined the database, updated postgrator files
validatechecksums is still false in app\database.js.

### CODE REVIEW

**Comment by judsona** [comment]
Give me a moment to look

**Comment by judsona** [comment]
Ah shit I see. You made two commits to main that aren’t in this branch. Both impacting files you have deleted. So merge is having trouble. 

You’ll need to resolve the merge using command line see ^^ above 

when you do it git will setup the merge and you will delete the two files again / choose your new change over mains. Then commit and push again

**Comment by judsona** [comment]
Sorry it is see below haha.

**Comment by Pprime1** [comment]
```
C:\Users\Peter\csasm>git fetch origin
fatal: 'origin' does not appear to be a git repository
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
C:\Users\Peter\csasm>
```

Might be easier if I just make the same changes in main and delete the problematic branch.

**Comment by judsona** [comment]
> ```
> C:\Users\Peter\csasm>git fetch origin
> fatal: 'origin' does not appear to be a git repository
> fatal: Could not read from remote repository.
> 
> Please make sure you have the correct access rights
> and the repository exists.
> C:\Users\Peter\csasm>
> ```
> 
> 
>      
>   
> 
> Might be easier if I just make the same changes in main and delete the problematic branch.

Have you checked the repo out? Or are you working another way?

**Comment by Pprime1** [comment]
I have been using the github website to date (I had stuff working and I can access what I am doing from any computer quickly) - so far I have used the command line just for the database work in the past week or so. I have been googling how to checkout a repo but so far I am just getting error messages. I guess this is another thing I need to learn about :-)

**Comment by judsona** [comment]
I merged it for you. I had to change a database file again. So it might cause the hash to change. Hopefully not

**Comment by Pprime1** [comment]
I have not been able to work out the hash stuff yet. Have abandoned that aspect for now (validatechecksums=false) as I wanted to get back into the main todo items

thankyou

**Pull request merged**
